In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas as pd

In [ ]:
file_path = '/content/Datos_Filtrados.csv'

In [ ]:
data = pd.read_csv(file_path)

In [ ]:
data

,ID_Viaje,Fecha,Ruta,Numero_Pasajeros,Duracion_Viaje_Minutos,Retraso_Minutos,Tipo_Transporte,Region,Dia_Semana
0,2,2023-01-01 00:01:00,Malaga - Sevilla,99.0,192.0,58,Tren,Barcelona,Sunday
1,3,2023-01-01 00:02:00,Madrid - Zaragoza,10.0,94.0,119,Autobús,Madrid,Sunday
2,5,2023-01-01 00:04:00,Madrid - Malaga,22.0,335.0,51,Autobús,Sevilla,Sunday
3,7,2023-01-01 00:06:00,Madrid - Malaga,78.0,608.0,21,Autobús,Malaga,Sunday
4,11,2023-01-01 00:10:00,Valencia - Sevilla,67.0,345.0,2,Autobús,Sevilla,Sunday
...,...,...,...,...,...,...,...,...,...
49999,99993,2023-03-11 10:32:00,Madrid - Barcelona,14.0,98.0,14,Tren,Barcelona,Saturday
50000,99994,2023-03-11 10:33:00,Valencia - Sevilla,38.0,715.0,108,Autobús,Zaragoza,Saturday
50001,99995,2023-03-11 10:34:00,Valencia - Sevilla,27.0,665.0,118,Autobús,Malaga,Saturday
50002,99996,2023-03-11 10:35:00,Malaga - Sevilla,89.0,566.0,38,Autobús,Valencia,Saturday
50003,99998,2023-03-11 10:37:00,Valencia - Sevilla,95.0,174.0,54,Tren,Valencia,Saturday

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50004 entries, 0 to 50003
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_Viaje                50004 non-null  int64
 1   Fecha                   50004 non-null  object
 2   Ruta                    50004 non-null  object
 3   Numero_Pasajeros        50004 non-null  float64
 4   Duracion_Viaje_Minutos  50004 non-null  float64
 5   Retraso_Minutos         50004 non-null  int64
 6   Tipo_Transporte         50004 non-null  object
 7   Region                  50004 non-null  object
 8   Dia_Semana              50004 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 3.4+ MB

In [ ]:
# Convertir Numero_Pasajeros a int
data['Numero_Pasajeros'] = data['Numero_Pasajeros'].astype(int)

In [ ]:
# Convertir fecha a datetime
data['Fecha'] = pd.to_datetime(data['Fecha'], format='%Y-%m-%d %H:%M:%S')

In [ ]:
# Convertir 'duracion_viaje_minutos' a float
data['Duracion_Viaje_Minutos'] = pd.to_numeric(data['Duracion_Viaje_Minutos'], errors='coerce')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50004 entries, 0 to 50003
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_Viaje                50004 non-null  int64
 1   Fecha                   50004 non-null  datetime64[ns]
 2   Ruta                    50004 non-null  object
 3   Numero_Pasajeros        50004 non-null  int64
 4   Duracion_Viaje_Minutos  50004 non-null  float64
 5   Retraso_Minutos         50004 non-null  int64
 6   Tipo_Transporte         50004 non-null  object
 7   Region                  50004 non-null  object
 8   Dia_Semana              50004 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 3.4+ MB

In [ ]:
# Filtrando los tipos de transporte inviables ('Tranvía' y 'Metro')
transportes_inviables = ['Tranvía', 'Metro']
data_filtrada = data[~data['Tipo_Transporte'].isin(transportes_inviables)]

# Mostrando un resumen de los datos filtrados para verificar
resumen_transporte = data_filtrada['Tipo_Transporte'].value_counts()
print(resumen_transporte)

Tipo_Transporte
Autobús    25050
Tren       24954
Name: count, dtype: int64

In [ ]:
# Filtrar retrasos anormalmente altos (999 minutos)
data_filtrada = data_filtrada[data_filtrada['Retraso_Minutos'] < 999]

print("Datos después del filtrado:")
# Mostrar una muestra de los datos filtrados
print(data_filtrada.head())

Datos después del filtrado:
   ID_Viaje               Fecha                Ruta  Numero_Pasajeros  \
0         2 2023-01-01 00:01:00    Malaga - Sevilla                99
1         3 2023-01-01 00:02:00   Madrid - Zaragoza                10
2         5 2023-01-01 00:04:00     Madrid - Malaga                22
3         7 2023-01-01 00:06:00     Madrid - Malaga                78
4        11 2023-01-01 00:10:00  Valencia - Sevilla                67

   Duracion_Viaje_Minutos  Retraso_Minutos Tipo_Transporte     Region  \
0                   192.0               58            Tren  Barcelona
1                    94.0              119         Autobús     Madrid
2                   335.0               51         Autobús    Sevilla
3                   608.0               21         Autobús     Malaga
4                   345.0                2         Autobús    Sevilla

  Dia_Semana
0     Sunday
1     Sunday
2     Sunday
3     Sunday
4     Sunday

In [ ]:
data_filtrada.head()

,ID_Viaje,Fecha,Ruta,Numero_Pasajeros,Duracion_Viaje_Minutos,Retraso_Minutos,Tipo_Transporte,Region,Dia_Semana
0,2,2023-01-01 00:01:00,Malaga - Sevilla,99,192.0,58,Tren,Barcelona,Sunday
1,3,2023-01-01 00:02:00,Madrid - Zaragoza,10,94.0,119,Autobús,Madrid,Sunday
2,5,2023-01-01 00:04:00,Madrid - Malaga,22,335.0,51,Autobús,Sevilla,Sunday
3,7,2023-01-01 00:06:00,Madrid - Malaga,78,608.0,21,Autobús,Malaga,Sunday
4,11,2023-01-01 00:10:00,Valencia - Sevilla,67,345.0,2,Autobús,Sevilla,Sunday

In [ ]:
data_filtrada.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49768 entries, 0 to 50003
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_Viaje                49768 non-null  int64
 1   Fecha                   49768 non-null  datetime64[ns]
 2   Ruta                    49768 non-null  object
 3   Numero_Pasajeros        49768 non-null  int64
 4   Duracion_Viaje_Minutos  49768 non-null  float64
 5   Retraso_Minutos         49768 non-null  int64
 6   Tipo_Transporte         49768 non-null  object
 7   Region                  49768 non-null  object
 8   Dia_Semana              49768 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 3.8+ MB

In [ ]:
# Guardar el DataFrame en un archivo CSV
file_path = '/content/data_final.csv'
data_filtrada.to_csv(file_path, index=False)

In [ ]:
import sqlite3

# Conectar a la base de datos SQLite (o crear una nueva)
conn = sqlite3.connect('transporte_publico.db')
c = conn.cursor()

# Crear la tabla
c.execute('''
CREATE TABLE IF NOT EXISTS transporte_publico (
    ID_Viaje INTEGER PRIMARY KEY,
    Fecha DATETIME,
    Ruta TEXT,
    Numero_Pasajeros INTEGER,
    Duracion_Viaje_Minutos FLOAT,
    Retraso_Minutos INTEGER,
    Tipo_Transporte TEXT,
    Region TEXT,
    Dia_Semana TEXT
)
''')

conn.commit()

In [ ]:
import pandas as pd

# Cargar los datos desde el archivo CSV
data = pd.read_csv('/content/data_final.csv')

# Convertir la columna Fecha a formato datetime
# data['Fecha'] = pd.to_datetime(data['Fecha'])

# Preparar los datos para la inserción
data_to_insert = data.values.tolist()

# Insertar los datos en la tabla
c.executemany('''
INSERT INTO transporte_publico
(ID_Viaje, Fecha, Ruta, Numero_Pasajeros, Duracion_Viaje_Minutos, Retraso_Minutos, Tipo_Transporte, Region, Dia_Semana)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
''', data_to_insert)

# Confirmar los cambios y cerrar la conexión
conn.commit()
conn.close()

In [ ]:
# Conectar a la base de datos SQLite
conn = sqlite3.connect('transporte_publico.db')
c = conn.cursor()

# Ejecutar una consulta SQL
c.execute('SELECT * FROM transporte_publico LIMIT 5')

# Obtener los resultados
rows = c.fetchall()

In [ ]:
# Convertir los resultados en un DataFrame de pandas
columns = [desc[0] for desc in c.description]
df = pd.DataFrame(rows, columns=columns)

# Mostrar el DataFrame
print(df)

   ID_Viaje                Fecha                Ruta  Numero_Pasajeros  \
0         2  2023-01-01 00:01:00    Malaga - Sevilla                99
1         3  2023-01-01 00:02:00   Madrid - Zaragoza                10
2         5  2023-01-01 00:04:00     Madrid - Malaga                22
3         7  2023-01-01 00:06:00     Madrid - Malaga                78
4        11  2023-01-01 00:10:00  Valencia - Sevilla                67

   Duracion_Viaje_Minutos  Retraso_Minutos Tipo_Transporte     Region  \
0                   192.0               58            Tren  Barcelona
1                    94.0              119         Autobús     Madrid
2                   335.0               51         Autobús    Sevilla
3                   608.0               21         Autobús     Malaga
4                   345.0                2         Autobús    Sevilla

  Dia_Semana
0     Sunday
1     Sunday
2     Sunday
3     Sunday
4     Sunday

In [8]:
# Cambios en archivo para su uso en Power BI
import pandas as pd
# Cargamos los datos
file_path = '/content/data_final.csv'
data = pd.read_csv(file_path)

# Vemos las priemras filas para entender su estructura
data.head()

,ID_Viaje,Fecha,Ruta,Numero_Pasajeros,Duracion_Viaje_Minutos,Retraso_Minutos,Tipo_Transporte,Region,Dia_Semana
0,2,2023-01-01 00:01:00,Malaga - Sevilla,99,192.0,58,Tren,Barcelona,Sunday
1,3,2023-01-01 00:02:00,Madrid - Zaragoza,10,94.0,119,Autobús,Madrid,Sunday
2,5,2023-01-01 00:04:00,Madrid - Malaga,22,335.0,51,Autobús,Sevilla,Sunday
3,7,2023-01-01 00:06:00,Madrid - Malaga,78,608.0,21,Autobús,Malaga,Sunday
4,11,2023-01-01 00:10:00,Valencia - Sevilla,67,345.0,2,Autobús,Sevilla,Sunday

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49768 entries, 0 to 49767
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID_Viaje                49768 non-null  int64
 1   Fecha                   49768 non-null  object
 2   Ruta                    49768 non-null  object
 3   Numero_Pasajeros        49768 non-null  int64
 4   Duracion_Viaje_Minutos  49768 non-null  float64
 5   Retraso_Minutos         49768 non-null  int64
 6   Tipo_Transporte         49768 non-null  object
 7   Region                  49768 non-null  object
 8   Dia_Semana              49768 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 3.4+ MB

In [10]:
# Convertiendo fecha a datetime
data['Fecha'] = pd.to_datetime(data['Fecha'], format='%Y-%m-%d %H:%M:%S')

In [11]:
# Asegurarnos que Duracion_Viaje_Minutos es float
data['Duracion_Viaje_Minutos'] = data['Duracion_Viaje_Minutos'].astype(float)

# Reemplazando punto decimal por coma para no tener conflicto en Power BI
data['Duracion_Viaje_Minutos'] = data['Duracion_Viaje_Minutos'].apply(lambda x: str(x).replace('.', ','))

In [12]:
data.head()

,ID_Viaje,Fecha,Ruta,Numero_Pasajeros,Duracion_Viaje_Minutos,Retraso_Minutos,Tipo_Transporte,Region,Dia_Semana
0,2,2023-01-01 00:01:00,Malaga - Sevilla,99,"192,0",58,Tren,Barcelona,Sunday
1,3,2023-01-01 00:02:00,Madrid - Zaragoza,10,"94,0",119,Autobús,Madrid,Sunday
2,5,2023-01-01 00:04:00,Madrid - Malaga,22,"335,0",51,Autobús,Sevilla,Sunday
3,7,2023-01-01 00:06:00,Madrid - Malaga,78,"608,0",21,Autobús,Malaga,Sunday
4,11,2023-01-01 00:10:00,Valencia - Sevilla,67,"345,0",2,Autobús,Sevilla,Sunday

In [15]:
# Guardar el DataFrame en un archivo CSV
file_path = '/content/data_transporte_final.csv'
data.to_csv(file_path, index=False)